package PedroLopes.tqs;
// Generated by Selenium IDE

import io.github.bonigarcia.seljup.SeleniumJupiter;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.interactions.Actions;

import static org.assertj.core.api.Assertions.assertThat;

@ExtendWith(SeleniumJupiter.class)
public class BuyTicketTest {
  
  @Test
  void test( FirefoxDriver driver ) {
    driver.get( "https://bonigarcia.dev/selenium-webdriver-java/" );
    assertThat( driver.getTitle() ).contains( "Selenium WebDriver" );
  }
  
  @Test
  public void buyTicket( FirefoxDriver driver ) {
    // Test name: BuyTicket
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get( "https://blazedemo.com/" );
    // 2 | setWindowSize | 1104x1028 | 
    driver.manage().window().setSize( new Dimension( 1104, 1028 ) );
    // 3 | select | name=fromPort | label=Philadelphia
    {
      WebElement dropdown = driver.findElement( By.name( "fromPort" ) );
      dropdown.findElement( By.xpath( "//option[. = 'Philadelphia']" ) ).click();
    }
    // 4 | mouseDownAt | name=fromPort | 0,0
    {
      WebElement element = driver.findElement( By.name( "fromPort" ) );
      Actions builder = new Actions( driver );
      builder.moveToElement( element ).clickAndHold().perform();
    }
    // 5 | mouseMoveAt | name=fromPort | 0,0
    {
      WebElement element = driver.findElement( By.name( "fromPort" ) );
      Actions builder = new Actions( driver );
      builder.moveToElement( element ).perform();
    }
    // 6 | mouseUpAt | name=fromPort | 0,0
    {
      WebElement element = driver.findElement( By.name( "fromPort" ) );
      Actions builder = new Actions( driver );
      builder.moveToElement( element ).release().perform();
    }
    // 7 | select | name=toPort | label=London
    {
      WebElement dropdown = driver.findElement( By.name( "toPort" ) );
      dropdown.findElement( By.xpath( "//option[. = 'London']" ) ).click();
    }
    // 8 | mouseDownAt | name=toPort | 0,0
    {
      WebElement element = driver.findElement( By.name( "toPort" ) );
      Actions builder = new Actions( driver );
      builder.moveToElement( element ).clickAndHold().perform();
    }
    // 9 | mouseMoveAt | name=toPort | 0,0
    {
      WebElement element = driver.findElement( By.name( "toPort" ) );
      Actions builder = new Actions( driver );
      builder.moveToElement( element ).perform();
    }
    // 10 | mouseUpAt | name=toPort | 0,0
    {
      WebElement element = driver.findElement( By.name( "toPort" ) );
      Actions builder = new Actions( driver );
      builder.moveToElement( element ).release().perform();
    }
    // 11 | click | css=.btn-primary | 
    driver.findElement( By.cssSelector( ".btn-primary" ) ).click();
    // 12 | click | css=tr:nth-child(3) .btn | 
    driver.findElement( By.cssSelector( "tr:nth-child(3) .btn" ) ).click();
    // 13 | click | id=inputName | 
    driver.findElement( By.id( "inputName" ) ).click();
    // 14 | type | id=inputName | Pedo
    driver.findElement( By.id( "inputName" ) ).sendKeys( "Pedo" );
    // 15 | type | id=address | LA
    driver.findElement( By.id( "address" ) ).sendKeys( "LA" );
    // 16 | type | id=city | asd
    driver.findElement( By.id( "city" ) ).sendKeys( "asd" );
    // 17 | type | id=state | asdf
    driver.findElement( By.id( "state" ) ).sendKeys( "asdf" );
    // 18 | type | id=zipCode | 12314
    driver.findElement( By.id( "zipCode" ) ).sendKeys( "12314" );
    // 19 | type | id=creditCardNumber | 123
    driver.findElement( By.id( "creditCardNumber" ) ).sendKeys( "123" );
    // 20 | type | id=nameOnCard | John Doe
    driver.findElement( By.id( "nameOnCard" ) ).sendKeys( "John Doe" );
    // 21 | click | id=rememberMe | 
    driver.findElement( By.id( "rememberMe" ) ).click();
    // 22 | click | css=.btn-primary | 
    driver.findElement( By.cssSelector( ".btn-primary" ) ).click();
    // 23 | click | css=pre | 
    driver.findElement( By.cssSelector( "pre" ) ).click();
    // 24 | assertTitle | BlazeDemo Confirmation | 
    assertThat( driver.getTitle() ).isEqualTo( "BlazeDemo Confirmation" );
  }
}
